### ISSUE TITLE
[BUG] False negatives in Jenkins CI

### ISSUE THREAD

**Issue by kanadgupta** [npm/ci-detect#47]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Right now, the Jenkins Pipeline detection solely relies on the existence of `JENKINS_URL` variable. Per [the Jenkins docs](https://www.jenkins.io/doc/book/pipeline/jenkinsfile/#using-environment-variables):

> (NOTE: only available if Jenkins URL set in "System Configuration")

For users that don't configure the Jenkins URL for their CI pipeline, this package returns a false negative.

### Expected Behavior

This package should always return `true` for Jenkins CI, so I propose adding a check for the `BUILD_ID` variable as an additional check for Jenkins since that value should always be there in Jenkins CI. This is what `ci-info` does: https://github.com/watson/ci-info/blob/master/vendors.json#L135

### Environment

- npm: 8.19.3
- Node: 16.14.0
- OS: macOS
- platform: MacBook Pro

**Comment by wraithgar** [comment]
Does `ci-info` correctly detect jenkins if both variables aren't set?  I dug through the code and it appears to be doing an `every` on that array, not an `any`.  It seems to me ci-info would have the same bug.

**Comment by wraithgar** [comment]
I added this test to ci-info's test.js file and it fails

```javascript
test('Jenkins - no JENKINS_URL set', function (t) {
  process.env.BUILD_ID = 'true'

  clearModule('./')
  const ci = require('./')

  t.equal(ci.isCI, true)
  t.equal(ci.name, 'Jenkins')
  t.equal(ci.JENKINS, true)
  assertVendorConstants('JENKINS', ci, t)

  delete process.env.BUILD_ID

  t.end()
})
```

**Comment by wraithgar** [comment]
I have [started a PR](https://github.com/watson/ci-info/pull/95) into ci-info to get to the bottom of this.  I see you have made a PR in your project to move to ci-info and that is probably the right choice.  Closing this in favor of triaging/fixing this (if needed) in ci-info.

**Comment by kanadgupta** [comment]
Appreciate you digging into this @wraithgar!

**Comment by wraithgar** [comment]
`npm@9.1.2` Uses `ci-info` now
